version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: sportshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: anhhadeptrai
      MYSQL_DATABASE: sports
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s


  app:
    build: .
    container_name: sportshop-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_ROOT_PASSWORD: anhhadeptrai
    ports:
      - "8080:8080"

volumes:
  db_data:
